"""RC house model, room offsets, backtests and simulations."""

from __future__ import annotations

import time
from datetime import UTC, datetime, timedelta
from types import SimpleNamespace

import numpy as np
import pytest
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert

from climate.models import backtest as bt
from climate.models import thermal_rc as rc
from climate.store.orm import ModelFit, Reading5m, Runtime5m, WeatherHour
from climate.timeutil import day_bounds_utc, local_date, utcnow
from tests.factories import make_history

TZ = "America/Chicago"
TRUE = rc.RCModel(
    mode="cool",
    main=np.array([0.06, 0.10, 0.03, 1.2, 3.0, 0.25]),
    up=np.array([0.08, 0.14, 0.10, 2.0, 3.5, 0.30]),
    bed=np.array([0.05, 0.05, 1.0, 2.8, 0.20]),
)
OCC_SENSORS = {"main": ["main.hallway_tstat", "main.school_room", "main.living_room", "main.kitchen"],
               "up": ["up.toy_room", "up.girls_room"], "bed": ["bed.bedroom_tstat", "bed.office"]}


def _insert(db, table, rows):
    for i in range(0, len(rows), 5000):
        db.execute(insert(table).values(rows[i : i + 5000]).on_conflict_do_nothing())
    db.flush()


def write_rc_history(db, model: rc.RCModel, end: datetime, days: int, seed: int = 3, sun_on: bool = True,
                     noise: float = 0.02) -> dict:
    """Synthetic history generated by the RC equations themselves (15-minute Euler steps, the
    ideal thermostat holding random setpoints), written the way ecobee reports it: three
    identical 5-minute runtime rows per 15-minute slot plus hourly Open-Meteo weather."""
    rng = np.random.default_rng(seed)
    start = end - timedelta(days=days)
    n = days * 96
    cloud_by_day = rng.uniform(0.2, 1.0, days + 2)
    weather = []
    t = start - timedelta(hours=3)
    while t <= end + timedelta(hours=3):
        local_h = (t.hour - 5) % 24 - 0.5  # preceding-hour mean centred half an hour earlier
        d = min(days + 1, max(0, (t - start).days))
        sw = max(0.0, np.sin((local_h - 6) / 12 * np.pi)) * 900.0 * cloud_by_day[d] if sun_on else 0.0
        weather.append(dict(ts=t, source="open-meteo", kind="observed", temp_f=80.0, rh=50.0, dewpoint_f=60.0,
                            cloud_cover=30.0, shortwave_wm2=float(sw), wind_mph=4.0, precip_in=0.0))
        t += timedelta(hours=1)
    _insert(db, WeatherHour, weather)
    _, sun, _, _ = rc.weather_inputs(db, start, n)  # exactly what the loader will see
    hours = np.arange(n) / 4.0
    local_h = (hours + start.hour - 5) % 24
    t_out = 80 + 9 * np.sin((local_h - 10) / 24 * 2 * np.pi) + 4 * np.sin(hours / 24 / 5.0) + rng.normal(0, 0.3, n)
    sp = np.empty((n, 3))
    for z in range(3):
        i = 0
        while i < n:
            span = int(rng.integers(8, 24))
            sp[i : i + span, z] = rng.choice([72, 74, 76, 78, 80, 86])
            i += span
    T, on = rc.emulate(model, np.array([[76.0, 77.0, 75.0]]), t_out[:, None], sun[:, None], sp[:, None, :])
    T = T[:-1, 0, :] + rng.normal(0, noise, (n, 3))
    on = on[:, 0, :]
    rows = []
    for k in range(n):
        for j in range(3):
            ts = start + timedelta(minutes=15 * k + 5 * j)
            for z, u in enumerate(rc.ZONES):
                secs = int(round(on[k, z] * 300))
                rows.append(dict(ts=ts, unit_key=u, comp_cool1=secs, comp_cool2=0, fan=secs, hvac_mode="cool",
                                 zone_temp_f=float(T[k, z]), cool_sp_f=float(sp[k, z]), heat_sp_f=68.0,
                                 outdoor_temp_f=float(t_out[k]), source="test"))
    _insert(db, Runtime5m, rows)
    return {"start": start, "n": n}


def _rel_err(fit_params: dict, truth: rc.RCModel) -> dict[str, float]:
    out = {}
    for z in rc.ZONES:
        for name, true in zip(rc.PARAM_NAMES[z], getattr(truth, z), strict=True):
            out[f"{z}.{name}"] = abs(fit_params["zones"][z][name] / true - 1)
    return out


END = datetime(2026, 7, 29, 5, 0, tzinfo=UTC)  # local midnight (CDT)


def test_fit_rc_recovers_known_parameters_and_beats_persistence(db):
    write_rc_history(db, TRUE, END, days=28)
    t0 = time.monotonic()
    ids = rc.fit_rc(db, END, days=28)
    assert time.monotonic() - t0 < 30
    assert len(ids) == 1  # only cooling has data
    fit = db.get(ModelFit, ids[0])
    assert fit.kind == "rc" and fit.mode == "cool" and fit.unit_key is None
    errs = _rel_err(fit.params, TRUE)
    assert max(errs.values()) < 0.25, errs
    m = fit.metrics
    assert m["rmse_1h"] < m["persistence_rmse_1h"] and m["rmse_1h"] <= 1.0
    assert m["rmse_24h"] is not None and m["n_points"] > 1500 and m["runtime_days"] >= 5
    assert m["runtime_err_rmse"] < 0.05
    assert fit.status == "active"
    assert fit.params["unidentified"] == []
    assert fit.params["physical"]["C"]["up"] == pytest.approx(0.10 / 0.14, rel=0.25)
    assert fit.train_end < local_date(END - timedelta(days=6), TZ)
    assert "pinned down" in fit.notes

    # a refit retires the previous active fit of the same mode
    ids2 = rc.fit_rc(db, END, days=28)
    assert db.get(ModelFit, ids[0]).status == "retired" and db.get(ModelFit, ids2[0]).status == "active"
    assert set(rc.active_rc(db)) == {"cool"}


def test_fit_rc_flags_parameters_without_excitation(db):
    write_rc_history(db, TRUE, END, days=21, sun_on=False, seed=5)
    ids = rc.fit_rc(db, END, days=21)
    fit = db.get(ModelFit, ids[0])
    assert {"main.sun", "up.sun", "bed.sun"} <= set(fit.params["unidentified"])
    assert "up.sun" in fit.notes and "Not pinned down" in fit.notes
    # everything that WAS excited is still recovered
    errs = _rel_err(fit.params, TRUE)
    assert max(v for k, v in errs.items() if not k.endswith(".sun")) < 0.25


def test_fit_rc_skips_without_enough_data(db):
    write_rc_history(db, TRUE, END, days=8)
    assert rc.fit_rc(db, END, days=8) == []  # one day of training is not enough


def test_fit_room_offsets_day_night(db):
    end = datetime(2026, 7, 10, 5, 0, tzinfo=UTC)
    start = end - timedelta(days=2)
    want = {"school_room": (1.5, 0.5), "kitchen": (-0.8, -0.3), "office": (2.0, 2.0), "hallway": (0.2, 0.2),
            "toy_room": (0.4, 0.1)}
    sensors = {"school_room": ["main.school_room"], "kitchen": ["main.kitchen"], "office": ["bed.office"],
               "hallway": ["main.hallway_tstat"], "toy_room": ["up.toy_room", "up.toy_room_tstat"]}
    unit_of = {"school_room": "main", "kitchen": "main", "office": "bed", "hallway": "main", "toy_room": "up"}
    zone = {"main": 76.0, "up": 77.0, "bed": 75.0}
    rt, rd = [], []
    t = start
    while t < end:
        local_h = (t.hour - 5) % 24
        night = local_h >= 21 or local_h < 7
        for u, z in zone.items():
            rt.append(dict(ts=t, unit_key=u, comp_cool1=120, zone_temp_f=z, cool_sp_f=z, heat_sp_f=68.0,
                           hvac_mode="cool", source="test"))
        for room, (day_off, night_off) in want.items():
            for skey in sensors[room]:
                rd.append(dict(ts=t, sensor_key=skey, temp_f=zone[unit_of[room]] + (night_off if night else day_off),
                               source="test"))
        t += timedelta(minutes=5)
    _insert(db, Runtime5m, rt)
    _insert(db, Reading5m, rd)
    first = rc.fit_room_offsets(db, end, days=2)
    fit_id = rc.fit_room_offsets(db, end, days=2)
    assert db.get(ModelFit, first).status == "retired"
    fit = db.get(ModelFit, fit_id)
    assert fit.kind == "room_offsets" and fit.status == "active"
    off = fit.params["offsets"]
    for room, (day_off, night_off) in want.items():
        assert off[room]["day"] == pytest.approx(day_off, abs=0.01)
        assert off[room]["night"] == pytest.approx(night_off, abs=0.01)
        assert fit.params["n"][room]["day"] > 0 and fit.params["n"][room]["night"] > 0
        assert fit.params["by_mode"][room]["cool"]["day"] == pytest.approx(day_off, abs=0.01)
    assert "twins_room" not in off and "foyer" not in off and "living_room" not in off  # no data / no sensor
    assert rc.fit_room_offsets(db, end - timedelta(days=30), days=2) is None


# ---------------------------------------------------------------------------------------
# backtest and simulate
# ---------------------------------------------------------------------------------------


def _baselines():
    return {(u, "cool"): SimpleNamespace(unit_key=u, mode="cool", balance_point_f=65.0, slope_s_per_dd=1800.0,
                                         intercept_s=600.0, cvrmse=0.12, resid_std_s=2400.0, resid_lag1=0.2)
            for u in ("main", "up", "bed")}


def _insert_active_rc(db, err=0.05):
    params = {"mode": "cool", "form": "rate", "dt_h": 0.25, "zones": TRUE.to_params()}
    db.add(ModelFit(kind="rc", mode="cool", params=params, status="active",
                    metrics={"rmse_1h": 0.3, "runtime_err_rmse": err, "runtime_err_scatter": err}))
    db.flush()


def test_backtest_rule_of_thumb_sign(db, monkeypatch):
    make_history(db, days=10)
    monkeypatch.setattr("climate.analytics.baseline.active_fits", lambda s: _baselines())
    same = bt.backtest(db, {}, days=7)
    assert same.model == "rule_of_thumb" and same.delta_pct == pytest.approx(0.0)
    assert same.beats_model_uncertainty is False
    cooler = bt.backtest(db, {"linked_offset_f": 3.0}, days=7)  # main floor 2°F cooler on empty afternoons
    assert cooler.model == "rule_of_thumb"
    assert cooler.candidate_runtime_min > cooler.current_runtime_min and cooler.delta_pct > 0
    assert cooler.comfort_violation_min_candidate is None and "floor coupling" in cooler.note
    warmer = bt.backtest(db, {"linked_floors_enabled": False}, days=7)  # main floats to away instead
    assert warmer.delta_pct < 0
    with pytest.raises(ValueError):
        bt.backtest(db, {"not_a_param": 1}, days=7)


def test_backtest_without_model_or_baselines(db, monkeypatch):
    make_history(db, days=3)
    monkeypatch.setattr("climate.analytics.baseline.active_fits", lambda s: {})
    out = bt.backtest(db, {"linked_offset_f": 2.0}, days=7)
    assert out.model == "rule_of_thumb" and out.delta_pct is None and not out.beats_model_uncertainty


def test_backtest_rc_path_sign_and_interval(db, monkeypatch):
    make_history(db, days=10)
    _insert_active_rc(db)
    monkeypatch.setattr("climate.analytics.baseline.active_fits", lambda s: {})
    same = bt.backtest(db, {}, days=7)
    assert same.model == "rc" and same.delta_pct == pytest.approx(0.0, abs=1e-9)
    assert same.beats_model_uncertainty is False
    out = bt.backtest(db, {"linked_offset_f": 3.0}, days=7)
    assert out.model == "rc" and out.days >= 6
    assert out.candidate_runtime_min > out.current_runtime_min and out.delta_pct > 0
    lo, hi = out.ci90_pct
    assert lo < out.delta_pct < hi
    assert out.comfort_violation_min_current is not None and out.comfort_violation_min_candidate is not None
    assert "Weather data by Open-Meteo.com" in out.note
    # a much less accurate model cannot claim the same difference
    db.execute(ModelFit.__table__.update().values(metrics={"runtime_err_rmse": 0.9, "runtime_err_scatter": 0.9}))
    vague = bt.backtest(db, {"linked_offset_f": 3.0}, days=7)
    assert vague.delta_pct == pytest.approx(out.delta_pct)
    assert vague.ci90_pct[1] - vague.ci90_pct[0] > hi - lo and not vague.beats_model_uncertainty


def test_simulate_rc_past_and_future_days(db, monkeypatch):
    make_history(db, days=10)
    _insert_active_rc(db)
    monkeypatch.setattr("climate.analytics.baseline.active_fits", lambda s: {})
    today = local_date(utcnow(), TZ)
    past = bt.simulate(db, {}, today - timedelta(days=2))
    assert past.model == "rc" and set(past.units) == {"main", "up", "bed"}
    start, end = day_bounds_utc(today - timedelta(days=2), TZ)
    n = int((end - start).total_seconds() // 900)
    assert all(len(p) == n for p in past.units.values())
    assert past.units["main"][0].ts == start and past.total_runtime_min > 0
    assert all(0 <= p.runtime_s <= 900 for pts in past.units.values() for p in pts)
    cooler = bt.simulate(db, {"linked_offset_f": 3.0}, today - timedelta(days=2))
    if (today - timedelta(days=2)).weekday() < 5:
        assert cooler.total_runtime_min > past.total_runtime_min
    future = bt.simulate(db, {})  # tomorrow: no forecast stored -> last week's weather
    assert future.model == "rc" and "last week" in future.note and future.total_runtime_min > 0


def test_simulate_rule_of_thumb(db, monkeypatch):
    make_history(db, days=10)
    monkeypatch.setattr("climate.analytics.baseline.active_fits", lambda s: _baselines())
    today = local_date(utcnow(), TZ)
    out = bt.simulate(db, {}, today - timedelta(days=1))
    assert out.model == "rule_of_thumb" and set(out.units) == {"main", "up", "bed"}
    assert out.total_runtime_min > 0 and "setpoints" in out.note
    assert {p.temp_f for p in out.units["up"]} <= {74.0, 77.0, 82.0}
